import { sql } from 'drizzle-orm';
import { notifications, events } from '../../../database/schema';
/** Apply lifecycle and privacy before pagination or counting. Never return source content. */
export function notificationVisibility(memberId: string, guest: boolean) {
  const project = (id: ReturnType<typeof sql>) =>
    sql`EXISTS(SELECT 1 FROM projects p WHERE p.id=${id} AND p.deleted_at IS NULL AND p.archived_at IS NULL AND ${!guest} AND NOT EXISTS(SELECT 1 FROM project_teams pt JOIN teams t ON t.id=pt.team_id WHERE pt.project_id=p.id AND (t.retired_at IS NOT NULL OR (t.visibility='PRIVATE' AND NOT EXISTS(SELECT 1 FROM team_memberships tm WHERE tm.team_id=t.id AND tm.membership_id=${memberId})))))`;
  const initiative = (id: ReturnType<typeof sql>) =>
    sql`EXISTS(SELECT 1 FROM initiatives i WHERE i.id=${id} AND i.deleted_at IS NULL AND i.archived_at IS NULL AND ${!guest} AND NOT EXISTS(SELECT 1 FROM initiative_projects ip WHERE ip.initiative_id=i.id AND NOT ${project(sql`ip.project_id`)}))`;
  const issue = sql`EXISTS(SELECT 1 FROM issues i WHERE i.id=${notifications.issueId} AND i.deleted_at IS NULL AND i.archived_at IS NULL AND NOT EXISTS(WITH RECURSIVE ancestry AS(SELECT i.id,i.parent_id,i.team_id,i.project_id,i.archived_at,i.deleted_at,0 depth UNION ALL SELECT p.id,p.parent_id,p.team_id,p.project_id,p.archived_at,p.deleted_at,a.depth+1 FROM issues p JOIN ancestry a ON p.id=a.parent_id WHERE a.depth<1000) SELECT 1 FROM ancestry a WHERE a.depth>=1000 OR a.archived_at IS NOT NULL OR a.deleted_at IS NOT NULL OR NOT EXISTS(SELECT 1 FROM teams t WHERE t.id=a.team_id AND t.retired_at IS NULL AND ((t.visibility='WORKSPACE' AND ${!guest}) OR EXISTS(SELECT 1 FROM team_memberships tm WHERE tm.team_id=t.id AND tm.membership_id=${memberId}))) OR(a.project_id IS NOT NULL AND NOT ${project(sql`a.project_id`)})))`;
  const document = sql`EXISTS(SELECT 1 FROM documents d WHERE d.id=${notifications.documentId} AND d.deleted_at IS NULL AND d.archived_at IS NULL AND ${!guest} AND (d.project_id IS NULL OR ${project(sql`d.project_id`)}) AND(d.initiative_id IS NULL OR ${initiative(sql`d.initiative_id`)}) AND(d.team_id IS NULL OR EXISTS(SELECT 1 FROM teams t WHERE t.id=d.team_id AND t.retired_at IS NULL AND(t.visibility='WORKSPACE' OR EXISTS(SELECT 1 FROM team_memberships tm WHERE tm.team_id=t.id AND tm.membership_id=${memberId})))))`;
  return sql`((${notifications.issueId} IS NOT NULL AND ${issue}) OR(${notifications.projectId} IS NOT NULL AND ${project(sql`${notifications.projectId}`)}) OR(${notifications.initiativeId} IS NOT NULL AND ${initiative(sql`${notifications.initiativeId}`)}) OR(${notifications.documentId} IS NOT NULL AND ${document})) AND EXISTS(SELECT 1 FROM ${events} source_event WHERE source_event.id=${notifications.eventId} AND(source_event.event_type NOT LIKE 'comment.%' OR EXISTS(SELECT 1 FROM comments c WHERE c.id=source_event.payload->>'comment_id' AND c.deleted_at IS NULL AND(c.project_update_id IS NULL OR EXISTS(SELECT 1 FROM project_updates c_pu WHERE c_pu.id=c.project_update_id AND c_pu.deleted_at IS NULL)) AND(c.initiative_update_id IS NULL OR EXISTS(SELECT 1 FROM initiative_updates c_iu WHERE c_iu.id=c.initiative_update_id AND c_iu.deleted_at IS NULL)))) AND(source_event.event_type<>'project.update_published' OR EXISTS(SELECT 1 FROM project_updates pu WHERE pu.id=source_event.payload->>'update_id' AND pu.deleted_at IS NULL)) AND(source_event.event_type<>'initiative.update_published' OR EXISTS(SELECT 1 FROM initiative_updates iu WHERE iu.id=source_event.payload->>'update_id' AND iu.deleted_at IS NULL)))`;
}
